---
name: publish
on:
  push:
    tags:
    - v*

jobs:
  publish:
    name: publish to npm
    runs-on: ubuntu-20.04

    steps:
    - name: "checkout code"
      uses: "actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f" # v2.3.4
    - name: "setup node"
      uses: "actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea" # v2.1.5
      with:
        node-version: "16.1.0"
    - name: "setup pnpm"
      run: "npm i -g pnpm@6.0.2"
    - name: "cache pnpm store"
      uses: "actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6" # v2.1.4
      with:
        path: "~/.pnpm-store"
        key: pnpm-store-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          pnpm-store-cache-${{ runner.os }}-
          pnpm-store-cache-
    - name: "install dependencies"
      run: "pnpm i"

    - name: build
      run: pnpm run build
    - name: "publish to npm"
      run: |
        cp .github/.npmrc .npmrc
        VERSION=${GITHUB_REF#refs/*/v} node .github/prepare.cjs
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
